const OK_STATUS = 200;
const CREATED_STATUS = 201;
const BAD_REQ_STATUS = 400;
const NOT_FOUND_PAGE_STATUS = 404;
const SERVER_ERROR_STATUS = 500;

module.exports = {
  OK_STATUS,
  CREATED_STATUS,
  BAD_REQ_STATUS,
  NOT_FOUND_PAGE_STATUS,
  SERVER_ERROR_STATUS,
};
